#!/usr/bin/env php
<?php

declare(strict_types=1);

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// 注册 Composer 自动加载
require __DIR__.'/vendor/autoload.php';

// Laravel 11：骨架核心在 bootstrap/app.php
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);